[platformio]
default_envs = heltec-v3

[env:heltec-v3]
platform = espressif32@6.12.0
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++17
    -DBONK_HELTEC_V3=1
    -DBONK_ENABLE_ADSB_OUT=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -Wall
    -Wextra

lib_deps =
    h2zero/NimBLE-Arduino@2.5.1
    adafruit/Adafruit GFX Library@1.12.6
    adafruit/Adafruit SSD1306@2.5.17
